//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaymentNotifier
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int NotificationId { get; set; }
        public int NotificationSettingsId { get; set; }
        public int Value { get; set; }
        public System.DateTime SentOn { get; set; }
    
        public virtual NotificationSettings NotificationSettings { get; set; }
    }
}
